baseurl = "//tyk.io/docs/"
languageCode = "en-gb"
title = "Tyk Documentation"
theme = "tykio"
MetaDataFormat = "yaml"
[blackfriday]
   plainIDAnchors = true
   hrefTargetBlank = true
[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"
